name: RecoveryBuilderRK3328

on:
  workflow_dispatch:
    inputs:
      MANIFEST_TYPE:
        description: 'MANIFEST_TYPE'
        required: true
        default: 'omni'
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git'
      MANIFEST_BRANCH:
        description: 'LIBRARY_BRANCH'
        required: true
        # default: 'twrp-9.0'
        default: 'twrp-5.1'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/rockchip-android/device-rockchip-rk3328'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'rk3328-box-7.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/rockchip/rk3328'
        # default: 'device/Android/rk3328_box'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'rk3328_box'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        docker rmi `docker images -q`
        #sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        #sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        #sudo apt -y autoremove --purge
        #sudo apt -y autoclean
        #sudo apt clean
        sudo apt update
        #sudo apt -y upgrade
        sudo apt -y install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev imagemagick libbz2-dev libssl-dev lzma ncftp bash-completion python openjdk-8-jdk qemu-user-static libc++-dev libc++abi-dev
      
    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var
      
    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH
      
    - name: Initialize repo
      run: |
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        echo "::set-output name=pwd::$(pwd)"
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }} -m rk3328_box_pie_release.xml
        
      id: pwd
          
    - name: Repo Sync
      run: |
        PATH=~/bin:$PATH
        cd workspace
        # repo sync -j$(nproc --all) -f --force-sync
        mkdir -p .repo/local_manifests
        #wget https://raw.githubusercontent.com/a9rock64/manifests/default/rk3328_box_pie_release.xml -O .repo/local_manifests/rk3328_box_pie_release.xml
        repo sync -j$(nproc --all) -f --force-sync -c --no-clone-bundle
        ls -al
      
    - name: Clone device tree
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        # git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        # MEEEEE
        #git clone https://github.com/rockchip-android/device-rockchip-rk3328.git -b rk3328-box-7.1 ./device/rockchip/rk3328
        #git clone https://github.com/rockchip-android/device-rockchip-common.git -b rk3328-box-7.1 ./device/rockchip/common
        #git clone https://github.com/rockchip-android/vendor-rockchip-common.git -b rk3328-box-7.1 ./vendor/rockchip/common
        #git clone https://github.com/rockchip-android/hardware-realtek -b rk3328-box-7.1 ./hardware/realtek
        ### git clone https://github.com/b-ghs/android_device_rockchip_rk3318.git device/Android/rk3318
        ### git clone https://github.com/b-ghs/android_device_rockchip_rk3318.git -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} device/Android/rk3318 
        ### rm -rf prebuilts/clang/host/linux-x86 && git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 prebuilts/clang/host/linux-x86 -b android-9.0.0_r61 --depth=1
        # rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
        echo "TW_USE_TOOLBOX := true" >> ${{ github.event.inputs.DEVICE_PATH }}/BoardConfig.mk
        
        rm -rf bootable/recovery && git clone https://github.com/rockchip-android/TWRP -b android-9.0 --depth 1 bootable/recovery
        
        # git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder

    - name: Building recovery
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        #lunch ${{ github.event.inputs.MANIFEST_TYPE }}_${{ github.event.inputs.DEVICE_NAME }}-eng
        lunch rk3328_box-userdebug
        echo "BOARD_TWRP_ENABLE := true" >> device/rockchip/common/device.mk
        make clean
        make recoveryimage -j$(nproc --all)        
      
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Recovery for ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
