name: Upload mega

on:
  workflow_dispatch

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf \
        libxml2 lzop pngcrush schedtool lzma ncftp \
        python wget lftp wimtools
        wget https://mega.nz/linux/repo/xUbuntu_18.04/amd64/megacmd-xUbuntu_18.04_amd64.deb
        sudo apt -y install ./megacmd-xUbuntu_18.04_amd64.deb
        # sudo apt-get -f install -y
        mkdir workspace

    - name: Write in folder
      run: |
        echo "Action" > text.txt
        dd if=/dev/urandom of=random.txt bs=500MB count=1
      working-directory: workspace

    - name: Disk usage
      run: |
        echo "Df -h"
        df -h
        echo "Du all"
        du -ahd1
        echo "Du -sh ."
        du -sh .
      working-directory: workspace
      
    - name: Compress folder
      run: |
        wimcapture workspace workspace.wim --threads=`nproc --all`
        rm -rf workspace
        filesize=$(du -k "workspace.wim" | cut -f 1)
        echo Filesize is $filesize
        if [ $actualsize -ge 55000000 ]; then
          exit 126
        fi

#     - name: Upload to mega
#       run: |
#         mega-cmd-server &>/dev/null &
#         sleep 5
#         mega-login ${{ secrets.MEGA_USER }} ${{ secrets.MEGA_PASSWORD }}
#         mega-ftp &
#         sleep 3
#         lftp ftp://127.0.0.1:4990 -e "put workspace.wim /"
#         mega-logout

    - name: Upload to mega
      run: |
        mega-cmd-server &>/dev/null &
        sleep 5
        mega-login ${{ secrets.MEGA_USER }} ${{ secrets.MEGA_PASSWORD }}
        mega-ftp /
        lftp ftp://127.0.0.1:4990 -e "put workspace.wim"
        mega-logout
        killall -s TERM mega-cmd-server


    - name: SSH to Actions126
      uses: P3TERX/ssh2actions@v1.0.0
